name: traffykai
channels:
  - conda-forge
dependencies:
  - python=3.11.16
  - pip
  - pip:
      - torch==2.9.0 --index-url https://download.pytorch.org/whl/cu126
      - torchvision==0.24.0 --index-url https://download.pytorch.org/whl/cu126
      - torchaudio==2.9.0 --index-url https://download.pytorch.org/whl/cu126
      - transformers==5.17.0
      - pandas==3.0.5
      - numpy==2.4.6
      - scikit-learn==1.9.0
      - scipy==1.17.1
      - pyarrow==25.0.0
      - joblib==1.6.0
